### ISSUE TITLE
[Bug]: Cursor gets stuck at end of line with multiple punctuation.

### ISSUE THREAD

**Issue by Aumnescio** [chrisgrieser/nvim-spider#11]
### Bug Description

Operation: `<Cmd>lua require('spider').motion('w')<CR>`

This motion operation gets stuck when the last "word" in a line of text consists of only punctuation.

### Reproduction & Sample Text

Before:

```
{( nested thing |)}
next line of text
```

After:

```
{( nested thing |)}
next line of text
```

Expected:

```
{( nested thing )}
|next line of text
```

Other example "Before" situations where the cursor gets stuck.

```
=== Title |===
next line of text
```

```
Haha |...
next line of text
```

### neovim version

```Text
NVIM v0.9.0-dev-2557+gfd32a9875-Homebrew
```

### Make sure you have done the following

- [X] In case I have an issue with using the motions in operater-pending mode (`cw`, `de`, …), I read the [notes on operator-pending mode in the README](https://github.com/chrisgrieser/nvim-spider#notes-on-operator-pending-mode).
- [X] I do not have set the options `virtualedit=all` or `virtualedit=onemore`.
- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
got it, fixed.

This is really hard, since there are *so many* off-by-ones to consider for this plugins  🙈
Probably due to lua using one-based indexes and vimscript using zero-based indexes

**Comment by Aumnescio** [comment]
Kind of hate to keep bothering you constantly, but I think the cursor still gets stuck if there are 3 or more punctuation characters. For 1 or 2 characters, it works.

Example cases:
(Bar '|' is cursor location.)

```
=== Title |===
Next line
```

```
OmegaNested |)))))))
Next line
```

Love the plugin though! And yeah, I've been struggling with Lua indexing too...
