### ISSUE TITLE
Feature Request: iw and aw

### ISSUE THREAD

**Issue by ivan-volnov** [chrisgrieser/nvim-spider#12]
### Feature Requested

Hi!

Thank you for the great plugin!

Please keep it small and simple in the future.

It also needs iw and aw implementation without any external plugins.

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
I already implemented iw and aw in another plugin, as linked in the readme. 

Adding it to this plugin as well would be redundant, sorry. 

Nvim-various-textobjs is, just like this plugin, fully written in lua, lightweight and easily lazyloaded.
