### ISSUE TITLE
[Bug]: Dot repeat is locking up the editor

### ISSUE THREAD

**Issue by utkarshgupta137** [chrisgrieser/nvim-spider#17]
### Bug Description

Dot repeat with `dew` (I've mapped spider's d/e/b to ed/ee/eb) for example, is locking up the editor until I press enter, after which I get the following error:

```
E5108: Error executing lua: attempt to call a nil value
stack traceback:
```

### Reproduction & Sample Text

Irrelevant

### neovim version

```Text
v0.9.0 (latest)
```

### Special Settings

```Text
lazy.vim:

return {
  "chrisgrieser/nvim-spider",
  keys = {
    { "ew", function() require("spider").motion("w") end, desc = "Spider-w", mode = { "n", "o", "x" } },
    { "ee", function() require("spider").motion("e") end, desc = "Spider-e", mode = { "n", "o", "x" } },
    { "eb", function() require("spider").motion("b") end, desc = "Spider-b", mode = { "n", "o", "x" } },
    { "ge", function() require("spider").motion("ge") end, desc = "Spider-ge", mode = { "n", "o", "x" } },
  },
  opts = {
    skipInsignificantPunctuation = false,
  },
}
```
```


### Make sure you have done the following

- [X] In case I have an issue with using the motions in operater-pending mode (`cw`, `de`, …), I read the [notes on operator-pending mode in the README](https://github.com/chrisgrieser/nvim-spider#notes-on-operator-pending-mode).
- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
see my response at #4

**Comment by utkarshgupta137** [comment]
@chrisgrieser I misstated in my comment in #4. The editor is locking up during dot-repeat, normal operation is just fine, so it wasn't off-topic.
Also, using lazy.vim's `keys` section to define keymaps isn't wrong. It works correctly for all plugins. LazyVim (the configuration framework) does the same thing: https://www.lazyvim.org/plugins/coding

**Comment by utkarshgupta137** [comment]
For future reference, the fix is to use Ex-commands as stated in the README, but I opened the issue because the editor locking up was really weird.

lazy.vim:
```lua
return {
  "chrisgrieser/nvim-spider",
  keys = {
    { "ew", "<cmd>lua require('spider').motion('w')<CR>", desc = "Spider-w", mode = { "n", "o", "x" } },
    { "ee", "<cmd>lua require('spider').motion('e')<CR>", desc = "Spider-e", mode = { "n", "o", "x" } },
    { "eb", "<cmd>lua require('spider').motion('b')<CR>", desc = "Spider-b", mode = { "n", "o", "x" } },
    { "ge", "<cmd>lua require('spider').motion('ge')<CR>", desc = "Spider-ge", mode = { "n", "o", "x" } },
  },
  opts = {
    skipInsignificantPunctuation = false,
  },
}
```

**Comment by chrisgrieser** [comment]
yes, vim behaves a little weird regarding dot-repeatability. But using the ex-commands seems to work fine.

If I understand you correctly, this issue is solved then, so I am closing this.

**Comment by utkarshgupta137** [comment]
Yeah, I should've read the readme again. I only commented on the PR because locking up is really weird behavior, but I miswrote & you closed it before I could clarify :)
Anyway, nice plugin.

**Comment by chrisgrieser** [comment]
thanks! and no worries. Glad it now works for you
