### ISSUE TITLE
[deleted]

### ISSUE THREAD

**Issue by TheSast** [chrisgrieser/nvim-spider#18]
### Bug Description

`<M-e>` (insert mode) does not work.
This only happens with this plugin enabled.
`<M-w>`, `<M-W>`, `<M-E>`, `<M-b>` and `<M-B>` work as expected.

### Reproduction & Sample Text

`<M-e>` 
before | after | expected |
--| -- | -- |
 tous les suj\|ets qui lui semblent | tous les suj\|ets qui lui semblent | tous les sujet\|**s** qui lui semblent |
INSERT | INSERT | NORMAL |

### neovim version

```Text
v0.9.0
```

### Special Settings

```Text
No
```

### Make sure you have done the following

- [X] In case I have an issue with using the motions in operater-pending mode (`cw`, `de`, …), I read the [notes on operator-pending mode in the README](https://github.com/chrisgrieser/nvim-spider#notes-on-operator-pending-mode).
- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
I think you misunderstood? 

This plugin is not designed for Insert mode, it only works in normal, visual, and operator-pending mode.

**Comment by TheSast** [comment]
Yeah but `<M-motion>` is dictated by the normal mode bind since it is by default bound to (something akin to) `<Esc>motion` with a few minor differences.
But I found out later that this is not due to this plugin alone.
