### ISSUE TITLE
[Bug]: ge mapping is slow

### ISSUE THREAD

**Issue by haoming-li-ling** [chrisgrieser/nvim-spider#2]
### Bug Description

w, e, and b mappings are snappy. However, there is a noticeable lag with the ge mapping.

### neovim version

```Text
0.8.3
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
Hmm, ge uses literally the same algorithm as the other movements, so there isn't really any reason why it should be slower. 

Could it be that you have some mapping that also starts with "ge", resulting in a delay since vim is waiting whether you press another key?

**Comment by haoming-li-ling** [comment]
I think you are right. I do have other mappings that start with ge. Closing this.
