### ISSUE TITLE
Feature Request:  Add W, (g)E and B

### ISSUE THREAD

**Issue by asyncedd** [chrisgrieser/nvim-spider#20]
### Feature Requested

Hey, first of all thanks for the plugin!

Right now, there's only motions for `w`, `e` and `b`. In (Neo)vim, there's also `W`, `E` and `B` too. I'd love to see them being added.

Thanks!

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
How are they supposed to differ from vim's version of W, E, and B?

**Comment by asyncedd** [comment]
Oh right! It doesn't really differ!
Sorry for disturbing
