### ISSUE TITLE
Feature Request: Word motion on camel case with capitalized acronyms

### ISSUE THREAD

**Issue by enigmassive** [chrisgrieser/nvim-spider#22]
### Feature Requested

At work, my team has a convention of using capitalized acronyms on camel case.

For example, we write `anHTTPRequest` instead of `anHttpRequest`.

Currently, `spider.motion("w")` would immediately move the cursor to `R` from the start.
With this feature, it would move the cursor to `H` first, then `R`  on the next call.

I have tried hacking together a solution myself: https://github.com/enigmassive/nvim-spider/commit/46c6be65c15431c920b7b2878d4be5e0b6439645.
It seems to generally work out so far, but it doesn't work on `e` nor `gE`.

I think it would be great if this feature could be properly implemented.
Thank you for considering.

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
Hi, this makes sense for me, but I somewhat fear that adding support for this edge case could unintentionally break some other edge cases. So before adding this, I'd like to add some tests. (see #25)

**Comment by backdround** [comment]
I've reimplemented the plugin and made a preset for the case. [neowords.nvim#sub-words-only](https://github.com/backdround/neowords.nvim#sub-words-only)

**Comment by chrisgrieser** [comment]
@enigmassive ugh, sorry, I made the preparatory work to fix this a while ago, but totally forgot to add the fix for this issue itself. Issue is fixed with the latest release.
