### ISSUE TITLE
Feature Request: support `wildfire.nvim`

### ISSUE THREAD

**Issue by NormTurtle** [chrisgrieser/nvim-spider#29]
### Feature Requested

[`wildfire.nvim`](https://github.com/SUSTech-data/wildfire.nvim/) - plugin for <cr> based `node` selection
**requested thing!**
- how to the [OG](https://github.com/SUSTech-data) dev can make `CamelCaseMotion` work for `visual-mode` as in `wildfire.nvim`
- describe help for word selection which is already inside of word as `CamelCaseMotion` for `Case`

here is the relevant [issue](https://github.com/SUSTech-data/wildfire.nvim/issues/2)
thank you !

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by NormTurtle** [comment]
this is more of a **Question** Rather a `issue`

**Comment by chrisgrieser** [comment]
Hi, yeah it's an issue for wildfire.nvim, not nvim-spider. I'll take a look at the other issue.
