### ISSUE TITLE
Feature Request: Add instructions for adding keymaps to lazy config

### ISSUE THREAD

**Issue by Anthony-Fiddes** [chrisgrieser/nvim-spider#30]
### Feature Requested

Since the default is for this plugin to be lazy loaded, maybe a section could be added explaining how to load the plugin when one of the motions is pressed? (I may be missing something super simple)

I found that my lazy config for the plugin looks like this:

```lua
    {
      "chrisgrieser/nvim-spider",
      keys = { "w", "e", "b", "ge" },
      config = function()
        vim.keymap.set({ "n", "o", "x" }, "w", "<cmd>lua require('spider').motion('w')<CR>", { desc = "Spider-w" })
        vim.keymap.set({ "n", "o", "x" }, "e", "<cmd>lua require('spider').motion('e')<CR>", { desc = "Spider-e" })
        vim.keymap.set({ "n", "o", "x" }, "b", "<cmd>lua require('spider').motion('b')<CR>", { desc = "Spider-b" })
        vim.keymap.set({ "n", "o", "x" }, "ge", "<cmd>lua require('spider').motion('ge')<CR>", { desc = "Spider-ge" })
      end,
      lazy = true,
    },
```

If I don't add the keymaps or set lazy=false, then the subword motions don't work.

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
can be easier done via `keys`. See the updated README

**Comment by Anthony-Fiddes** [comment]
The change is awesome, thanks!
