### ISSUE TITLE
[Bug]:  Bugs when camelCase names have numbers in them

### ISSUE THREAD

**Issue by leg7** [chrisgrieser/nvim-spider#31]
### Bug Description

w and b skip over the number

example (^ are the positions the cursor jumps to with w and b)

```
divisibleBy10Test
^--------^---^
```

end skips over subword before number

example:

```
divisibleBy10Test
--------^---^---^
```

kebab-case works as expected.

### Reproduction & Sample Text

...

### neovim version

```Text
0.9.4
```

### Special Settings

```Text
not that I know of.
```

### Make sure you have done the following

- [X] In case I have an issue with using the motions in operater-pending mode (`cw`, `de`, …), I read the [notes on operator-pending mode in the README](https://github.com/chrisgrieser/nvim-spider#notes-on-operator-pending-mode).
- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
Ah, good call, actually never noticed since I rarely have numbers in my camelCase words. Fixed.
