### ISSUE TITLE
Feature Request: Support subword delete in insert mode like CTRL-W

### ISSUE THREAD

**Issue by gh-liu** [chrisgrieser/nvim-spider#34]
### Feature Requested

CTRL-W will delete the word before the cursor, could this plugin support remap CTRL-W to delete subword?

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
Hi! You can actually already achieve that with a simple remap:

```lua
vim.keymap.set("i", "<C-w>", "<Esc>cb")
```
