### ISSUE TITLE
Feature Request: Pull in .editorconfig from your template repository

### ISSUE THREAD

**Issue by jwhitley** [chrisgrieser/nvim-spider#37]
### Feature Requested

Having adopted nvim-spider then  digging into its code a little, I noted that it uses hard tabs but there's no `.editorconfig` file in this repository.  It looks like the suitable editorconfig was added to your plugin template repo after this plugin's creation. It'd be great to see that file added here, to make contributors' lives easier when working on PRs.

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
good point. Bit annoying to keep up everything consistent with so many (small) repos I am maintaining 😅 

Anyway, config files are all updates
