### ISSUE TITLE
Feature Request: Add WORD motions

### ISSUE THREAD

**Issue by ray-x** [chrisgrieser/nvim-spider#42]
### Feature Requested

related to https://github.com/chrisgrieser/nvim-spider/issues/20

I am currently using chaoren/vim-wordmotion,   it allows me define `uppercase_space`

one example I defined `=` as an uppercase_space when I use `W` with `vim-wordmotion`

```
my_var_name=another_var_name
^___________^
```
Also I added '/' as a uppercase_space
so 
```
`chrisgrieser/nvim-spider`
 ^____________^
```

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
That sounds like a bit of a niche case. Couldn't you cover this via a custom pattern? https://github.com/chrisgrieser/nvim-spider?tab=readme-ov-file#advanced-custom-movement-patterns

**Comment by ray-x** [comment]
I am not quite sure customPatterns can do the job.
In the doc and code. customPatterns is a list and apply to `w` motion. How to change `W` motion behavior?

**Comment by chrisgrieser** [comment]
> customPatterns is a list and apply to w motion.

Well, nothing stopping you from giving the list only one element. 

And `"w"` as argument for the spider motions means just "go to next beginning of matching pattern". You can simply map that to `W`. 

Your first example, `my_var_name=another_var_name`, could be implemented with something like this:

```lua
vim.keymap.set("n", "W", function()
	local pattern = "[%w_]+"
	require("spider").motion("w", {
		customPatterns = { pattern },
	})
end, { desc = "spider-W-motion" })
```
