### ISSUE TITLE
[Bug]: consistent operator pending mode has no effect for me

### ISSUE THREAD

**Issue by PrayagS** [chrisgrieser/nvim-spider#46]
### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.
- [X] I have read the README.
- [X] If the issue is about `cw` or `dw`, I have read [the note on `w` in operator pending mode](https://github.com/chrisgrieser/nvim-spider#operator-pending-mode-the-case-of-cw).

### Bug Description

Whether I set `consistentOperatorPending` to true or false, I don't see any change in the behavior of motions.

My configuration is as follows,
```lua
{
	"chrisgrieser/nvim-spider",
	lazy = false,
	opts = {
		consistentOperatorPending = true,
	},
	config = function(_, opts)
		vim.keymap.set({ "n", "o", "x" }, "w", "<cmd>lua require('spider').motion('w')<CR>", { desc = "Spider-w" })
		vim.keymap.set({ "n", "o", "x" }, "e", "<cmd>lua require('spider').motion('e')<CR>", { desc = "Spider-e" })
		vim.keymap.set({ "n", "o", "x" }, "b", "<cmd>lua require('spider').motion('b')<CR>", { desc = "Spider-b" })
		-- See: https://github.com/chrisgrieser/nvim-spider#operator-pending-mode-the-case-of-cw
		vim.keymap.set("n", "cw", "ce", { remap = true })
	end,
},
```

### Reproduction & Sample Text

operation used: `dw`
before:
```
foo bar
--  ^
baz
```
after:
```
foo
   ^
--
baz
```

What I expected as per what I understood from the README,
```
foo baz
    ^
```

### neovim version

```Text
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713484068
```

**Comment by PrayagS** [comment]
Turns out Lazy is behaving weirdly here. Hasn't happened with me for other plugins, maybe it has something do with `lazy = false`.

I changed the config as follows and now it works as expected,
```lua
{
	"chrisgrieser/nvim-spider",
	lazy = false,
	-- opts = {
	-- 	consistentOperatorPending = true,
	-- },
	config = function()
		require("spider").setup({
			consistentOperatorPending = true,
		})
		vim.keymap.set({ "n", "o", "x" }, "w", "<cmd>lua require('spider').motion('w')<CR>", { desc = "Spider-w" })
		vim.keymap.set({ "n", "o", "x" }, "e", "<cmd>lua require('spider').motion('e')<CR>", { desc = "Spider-e" })
		vim.keymap.set({ "n", "o", "x" }, "b", "<cmd>lua require('spider').motion('b')<CR>", { desc = "Spider-b" })
		-- See: https://github.com/chrisgrieser/nvim-spider#operator-pending-mode-the-case-of-cw
		vim.keymap.set("n", "cw", "ce", { remap = true })
	end,
},
```

**Comment by chrisgrieser** [comment]
That's cause `opts` it's overridden by `config`. Usually you shouldn't use both of them at the same time. See the lazy.nvim readme
