### ISSUE TITLE
[Bug]: Last word in line has off-by-one with operators

### ISSUE THREAD

**Issue by jgollenz** [chrisgrieser/nvim-spider#5]
### Bug Description

```
// no trailing whitespace in the line below
nvim-spider is great
               ^
```
Doing e.g. `ce` will leave you with
```
nvim-spider is t
               ^
```

It works fine when there is a trailing whitespace

### neovim version

```Text
v0.9.0-dev-1312+g908494889
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
oh boy, vim indeed has some weird quirks when it comes to indeces. Fixed

**Comment by jgollenz** [comment]
Indeed. Interesting how one never notices these things until they change :grin: thanks a lot for the quick fix!
