### ISSUE TITLE
Feature Request: Update README for vim-plug users

### ISSUE THREAD

**Issue by guru245** [chrisgrieser/nvim-spider#51]
### Feature Requested

The README describes Installation only for Lazy.nvim and packer users. I tried to use this plugin with vim-plug, but it's not working for inexplicable reasons. If README is revised, it would be very helpful for vim-plug users.

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
I never used vim-plug, so I am unfortunately not familiar with it. If anyone uses vim-plug, feel free to make a PR?

**Comment by guru245** [comment]
Thanks for the prompt response. I will try to resolve this and make a PR. Thanks.

**Comment by guru245** [comment]
I found out that the issue where spider is not working has nothing to do with `vim-plug` plugin manager.  I guess some of the other setting in my environment is preventing spider. Therefore, you can close this task.

If you want to update README for vim-plug users, you can just add this:
`Plug("chrisgrieser/nvim-spider")`

Or I can send you a PR if you want.

Thank you.

**Comment by chrisgrieser** [comment]
on mobile rn, so a PR would be welcome!
